networks:
  eros-girnet:
    name: eros-girnet
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./req/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - eros-girnet

  mariadb:
    container_name: mariadb
    build:
      context: ./req/mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - eros-girnet
    env_file:
      - .env
  
  wordpress:
    container_name: wordpress
    build: ./req/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - eros-girnet
    env_file:
      - .env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eros-gir/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eros-gir/data/mysql